### ISSUE TITLE
Error when reading 'bin/main.dart': The system cannot find the path specified

### ISSUE THREAD

**Issue by matigumma** [YevhenKap/ai#2]
Error: Error when reading 'bin/main.dart': The system cannot find the path specified.

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1203:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#12     VMService.routeRequest (dart:_vmservice)
<asynchronous suspension>
#13     Client.onRequest (dart:_vmservice/client.dart:44:13)
#14     WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:52:13)
#15     new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#29     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#35     _StreamController._add (dart:async/stream_controller.dart:639:7)
#36     _StreamController.add (dart:async/stream_controller.dart:585:5)
#37     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#42     _StreamController._add (dart:async/stream_controller.dart:639:7)
#43     _StreamController.add (dart:async/stream_controller.dart:585:5)
#44     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1203:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#12     VMService.routeRequest (dart:_vmservice)
<asynchronous suspension>
#13     Client.onRequest (dart:_vmservice/client.dart:44:13)
#14     WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:52:13)
#15     new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#29     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#35     _StreamController._add (dart:async/stream_controller.dart:639:7)
#36     _StreamController.add (dart:async/stream_controller.dart:585:5)
#37     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#42     _StreamController._add (dart:async/stream_controller.dart:639:7)
#43     _StreamController.add (dart:async/stream_controller.dart:585:5)
#44     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1203:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#12     VMService.routeRequest (dart:_vmservice)
<asynchronous suspension>
#13     Client.onRequest (dart:_vmservice/client.dart:44:13)
#14     WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:52:13)
#15     new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#29     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#35     _StreamController._add (dart:async/stream_controller.dart:639:7)
#36     _StreamController.add (dart:async/stream_controller.dart:585:5)
#37     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#42     _StreamController._add (dart:async/stream_controller.dart:639:7)
#43     _StreamController.add (dart:async/stream_controller.dart:585:5)
#44     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.addUtf8Text (dart:_http/websocket_impl.dart:1210:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:81:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#12     VMService.routeRequest (dart:_vmservice)
<asynchronous suspension>
#13     Client.onRequest (dart:_vmservice/client.dart:44:13)
#14     WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:52:13)
#15     new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#29     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#35     _StreamController._add (dart:async/stream_controller.dart:639:7)
#36     _StreamController.add (dart:async/stream_controller.dart:585:5)
#37     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#42     _StreamController._add (dart:async/stream_controller.dart:639:7)
#43     _StreamController.add (dart:async/stream_controller.dart:585:5)
#44     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#45     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

Exited (254)

**Comment by Kapelianovych** [comment]
Hello. Thanks for your issue, but can you be more concrete? I cannot figure what exactly produces an error. And are you sure that error produce the `ai` package?
